name: Auto Merger for Dependabot 
on:
  pull_request:
    branches: [ master ]
jobs:
  # This workflow contains a single job called "build"
  automerge:
    name: Merge pull request
    runs-on: [ubuntu-latest]
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Merge
        uses: actions/github-script@0.2.0
        with:
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{secrets.GITHUB_TOKEN}}
